name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.x # latest stable version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: go test ./...
